gpu_device_info {
  threads_per_block_limit: 1024
  threads_per_warp: 32
  shared_memory_per_block: 49152
  shared_memory_per_core: 102400
  threads_per_core_limit: 1536
  core_count: 24
  fpus_per_core: 128
  block_dim_limit_x: 2147483647
  block_dim_limit_y: 65535
  block_dim_limit_z: 65535
  memory_bandwidth: 272032000000
  l2_cache_size: 25165824
  clock_rate_ghz: 2.475
  device_memory_size: 8585216000
  shared_memory_per_block_optin: 101376
  cuda_compute_capability {
    major: 8
    minor: 9
  }
  registers_per_core_limit: 65536
  registers_per_block_limit: 65536
}
platform_name: "CUDA"
dnn_version_info {
  major: 9
  minor: 10
  patch: 2
}
device_description_str: "NVIDIA GeForce RTX 4060"
runtime_version {
  major: 12
  minor: 5
}
